// Code generated by github.com/vektah/gqlgen, DO NOT EDIT.

package gettingstarted

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
